glpsol -m small/small_n00.in.mod
glpsol -m small/small_n01.in.mod
glpsol -m small/small_n02.in.mod
glpsol -m small/small_n03.in.mod
glpsol -m small/small_n04.in.mod
glpsol -m small/small_n05.in.mod
glpsol -m small/small_n06.in.mod
glpsol -m small/small_n07.in.mod
glpsol -m small/small_n08.in.mod
glpsol -m small/small_n09.in.mod
glpsol -m small/small_n10.in.mod
glpsol -m small/small_n11.in.mod
glpsol -m small/small_n12.in.mod
glpsol -m small/small_n13.in.mod
glpsol -m small/small_n14.in.mod
glpsol -m small/small_n15.in.mod
glpsol -m small/small_n16.in.mod
glpsol -m small/small_n17.in.mod
glpsol -m small/small_n18.in.mod
glpsol -m small/small_n19.in.mod