glpsol -m uniform/uniform_n00.in.mod
glpsol -m uniform/uniform_n01.in.mod
glpsol -m uniform/uniform_n02.in.mod
glpsol -m uniform/uniform_n03.in.mod
glpsol -m uniform/uniform_n04.in.mod
glpsol -m uniform/uniform_n05.in.mod
glpsol -m uniform/uniform_n06.in.mod
glpsol -m uniform/uniform_n07.in.mod
glpsol -m uniform/uniform_n08.in.mod
glpsol -m uniform/uniform_n09.in.mod
glpsol -m uniform/uniform_n10.in.mod
glpsol -m uniform/uniform_n11.in.mod
glpsol -m uniform/uniform_n12.in.mod
glpsol -m uniform/uniform_n13.in.mod
glpsol -m uniform/uniform_n14.in.mod
glpsol -m uniform/uniform_n15.in.mod
glpsol -m uniform/uniform_n16.in.mod
glpsol -m uniform/uniform_n17.in.mod
glpsol -m uniform/uniform_n18.in.mod
glpsol -m uniform/uniform_n19.in.mod
glpsol -m uniform/uniform_n20.in.mod
glpsol -m uniform/uniform_n21.in.mod
glpsol -m uniform/uniform_n22.in.mod
glpsol -m uniform/uniform_n23.in.mod
glpsol -m uniform/uniform_n24.in.mod
glpsol -m uniform/uniform_n25.in.mod
glpsol -m uniform/uniform_n26.in.mod
glpsol -m uniform/uniform_n27.in.mod
glpsol -m uniform/uniform_n28.in.mod
glpsol -m uniform/uniform_n29.in.mod
glpsol -m uniform/uniform_n30.in.mod
glpsol -m uniform/uniform_n31.in.mod
glpsol -m uniform/uniform_n32.in.mod
glpsol -m uniform/uniform_n33.in.mod
glpsol -m uniform/uniform_n34.in.mod
glpsol -m uniform/uniform_n35.in.mod
glpsol -m uniform/uniform_n36.in.mod
glpsol -m uniform/uniform_n37.in.mod
glpsol -m uniform/uniform_n38.in.mod
glpsol -m uniform/uniform_n39.in.mod
glpsol -m uniform/uniform_n40.in.mod
glpsol -m uniform/uniform_n41.in.mod
glpsol -m uniform/uniform_n42.in.mod
glpsol -m uniform/uniform_n43.in.mod
glpsol -m uniform/uniform_n44.in.mod
glpsol -m uniform/uniform_n45.in.mod
glpsol -m uniform/uniform_n46.in.mod
glpsol -m uniform/uniform_n47.in.mod
glpsol -m uniform/uniform_n48.in.mod
glpsol -m uniform/uniform_n49.in.mod
glpsol -m uniform/uniform_n50.in.mod
glpsol -m uniform/uniform_n51.in.mod
glpsol -m uniform/uniform_n52.in.mod
glpsol -m uniform/uniform_n53.in.mod
glpsol -m uniform/uniform_n54.in.mod
glpsol -m uniform/uniform_n55.in.mod
glpsol -m uniform/uniform_n56.in.mod
glpsol -m uniform/uniform_n57.in.mod
glpsol -m uniform/uniform_n58.in.mod
glpsol -m uniform/uniform_n59.in.mod
glpsol -m uniform/uniform_n60.in.mod
glpsol -m uniform/uniform_n61.in.mod
glpsol -m uniform/uniform_n62.in.mod
glpsol -m uniform/uniform_n63.in.mod
glpsol -m uniform/uniform_n64.in.mod
glpsol -m uniform/uniform_n65.in.mod
glpsol -m uniform/uniform_n66.in.mod
glpsol -m uniform/uniform_n67.in.mod
glpsol -m uniform/uniform_n68.in.mod
glpsol -m uniform/uniform_n69.in.mod
glpsol -m uniform/uniform_n70.in.mod
glpsol -m uniform/uniform_n71.in.mod
glpsol -m uniform/uniform_n72.in.mod
glpsol -m uniform/uniform_n73.in.mod
glpsol -m uniform/uniform_n74.in.mod
glpsol -m uniform/uniform_n75.in.mod
glpsol -m uniform/uniform_n76.in.mod
glpsol -m uniform/uniform_n77.in.mod
glpsol -m uniform/uniform_n78.in.mod
glpsol -m uniform/uniform_n79.in.mod
glpsol -m uniform/uniform_n80.in.mod
glpsol -m uniform/uniform_n81.in.mod
glpsol -m uniform/uniform_n82.in.mod
glpsol -m uniform/uniform_n83.in.mod
glpsol -m uniform/uniform_n84.in.mod
glpsol -m uniform/uniform_n85.in.mod
glpsol -m uniform/uniform_n86.in.mod
glpsol -m uniform/uniform_n87.in.mod
glpsol -m uniform/uniform_n88.in.mod
glpsol -m uniform/uniform_n89.in.mod
glpsol -m uniform/uniform_n90.in.mod
glpsol -m uniform/uniform_n91.in.mod
glpsol -m uniform/uniform_n92.in.mod
glpsol -m uniform/uniform_n93.in.mod
glpsol -m uniform/uniform_n94.in.mod
glpsol -m uniform/uniform_n95.in.mod
glpsol -m uniform/uniform_n96.in.mod
glpsol -m uniform/uniform_n97.in.mod
glpsol -m uniform/uniform_n98.in.mod
glpsol -m uniform/uniform_n99.in.mod